export default {
    /* COLORS */
    PRIMARY_COLOR: '#0c1e34', //DEEP BLUE
    SECONDARY_COLOR: '#ec695c', //POM
    BACKGROUND_COLOR: '#FFFFFF',
    SURFACE_COLOR: '#f7f8fb', //
    ERROR_COLOR: '#B00020',
    BORDER_COLOR: 'rgba(0,0,0,.07)',
    TEXT_ON_PRIMARY_COLOR: '#EFEDD8',
    TEXT_ON_SECONDARY_COLOR: '#FFFFFF',
    TEXT_ON_SURFACE_COLOR: '#000000',
    TEXT_ON_SURFACE_COLOR_LIGHT: 'rgba(0,0,0,.6)',
    TEXT_ON_ERROR:  '#FFFFFF',
    DISABLED_BG: '#343434',
    DISABLED_TEXT: '#A0A0A0',
    WHITE: '#FFFFFF',

    /* FONTS */
    FONT_LIGHT: 'Roboto_300Light',
    FONT_STANDARD: 'Roboto_400Regular',
    FONT_MEDIUM: 'Roboto_500Medium',
    FONT_BOLD: 'Roboto_700Bold',
    FONT_HEADER: 'NotoSerif_400Regular',
    HEADER_FONT_SIZE: 22,
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_MEDIUM_PLUS: 20,
    FONT_SIZE_LARGE: 24,
    FONT_SIZE_XL: 36,
    FONT_SIZE_XXL: 48,
    LINE_HEIGHT: 24,
    FONT_WEIGHT_LIGHT: "200",
    FONT_WEIGHT_MEDIUM: "500",
    FONT_WEIGHT_HEAVY: "800"
};