export default {
    /* COLORS */
    PRIMARY_COLOR: '#0c1e34', //DEEP BLUE
    PRIMARY_COLOR_FAINT: '#CCD8E4',
    SECONDARY_COLOR: '#ec695c', //POM
    SECONDARY_COLOR_LIGHT: 'rgb(250,214,211)', //POM LIGHT
    BACKGROUND_COLOR: '#FFFFFF',
    SURFACE_COLOR: '#FFFFFF', //
    SURFACE_COLOR_LIGHT: 'rgba(74,74,74,.2)',
    ERROR_COLOR: '#B00020',
    BORDER_COLOR:  '#CED8E3',     //'rgba(0,0,0,.07)',
    TEXT_ON_PRIMARY_COLOR: '#EFEDD8',
    TEXT_ON_SECONDARY_COLOR: '#FFFFFF',
    TEXT_ON_SURFACE_COLOR: '#0c1e34',
    TEXT_ON_SURFACE_COLOR_LIGHT: '#69727c',
    TEXT_ON_ERROR:  '#FFFFFF',
    DISABLED_BG: '#343434',
    DISABLED_TEXT: '#A0A0A0',
    WHITE: '#FFFFFF',
    GRAY: '#aaaaaa',
    FAINT: 'rgba(74,74,74,.4)',

    /* FONTS */
    FONT_LIGHT: 'Roboto_300Light',
    FONT_STANDARD: 'Roboto_400Regular',
    FONT_MEDIUM: 'Roboto_500Medium',
    FONT_BOLD: 'Roboto_700Bold',
    FONT_HEADER: 'NotoSerif_400Regular',
    HEADER_FONT_SIZE: 22,
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 16,
    FONT_SIZE_MEDIUM_PLUS: 19,
    FONT_SIZE_LARGE: 22,
    FONT_SIZE_XL: 27,
    FONT_SIZE_XXL: 48,
    LINE_HEIGHT: 24,
    FONT_WEIGHT_LIGHT: "200",
    FONT_WEIGHT_MEDIUM: "500",
    FONT_WEIGHT_HEAVY: "800"
};